SELECT
  IdentifierHash,
  Country,
  CAST(Users_productsSold AS INT) AS Users_productsSold,
  CAST(Users_productsWished AS INT) AS Users_productsWished,
  Users_hasanyapp,
  Users_socialnbfollowers,
  Countries_Sellers,
  Countries_TopSellers,
  Countries_FemaleSellers,
  Countries_MaleSellers,
  Countries_TopFemaleSellers,
  Countries_TopMaleSellers,
  Buyers_Total,
  Buyers_Top,
  Buyers_Female,
  Buyers_Male,
  Buyers_TopFemale,
  Buyers_TopMale,
  Sellers_Total,
  Sellers_MeanProductsSold,
  Sellers_MeanProductsListed,
  CASE WHEN Users_hasanyapp = true THEN 'Has App' ELSE 'No App' END AS app_status,
  CASE WHEN Users_hasanyapp = true THEN 1 ELSE 0 END AS has_app_flag
FROM ecom_db_kyle.default.gold_ecom_users
